using System.Collections;
using System.Collections.Generic;
using UnityEngine.SceneManagement;
using UnityEngine;

/* KillPlayer Class
** Maneja los triggers para indicarle al Minotauro que atrap√≥ al Player
*/
public class KillPlayer : MonoBehaviour
{   
    //************************** Events **************************//
    void OnTriggerEnter(Collider other) {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    
    // void OnControllerColliderHit(ControllerColliderHit hit)
    // {
    //     if(hit.gameObject.tag == "Player") {

    //         SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    //     }
    // }
}
